### PR TITLE
Updated To Phoenix 6

### PR DESCRIPTION
**Pull request by PickleFace5**
Creating this now since we're almost there!

The following needs to be done before we can merge:

- [x] Working Autonomous
- [x] Hockey Stop in Teleop
- [x] Use of Continuous Wrap for direction motors

I'm aiming to have everything done by **Saturday, February 3rd, 2024.**

### CODE REVIEW

**Comment by cwstryker** [comment]
It would be useful to have this code merged before the end of the day on Friday.  The only real requirement ifor a Friday merge is functional teleop capability. Everything else is extra butter.  Tasty, but not strictly necessary. 😉

**Comment by PickleFace5** [comment]
True, however I've set the deadline for all swerve development to be done by this Saturday, then we'll hard pivot to getting our other subsystems done. Since we're very close to have a working auto, I'm attempting to squeeze in autonomous and more tuning before I merge this into main.

**Comment by cwstryker** [comment]
Understood.

**Comment by PickleFace5** [comment]
I plan to merge this tomorrow at practice, planning to add continuous wrap to the direction motor and merge what we have into main.

**Comment by PickleFace5** [comment]
Alright, although continuous wrap has yet to be implemented, after Stemnasium I'm confident in the progress made with swerve drive thus far. I'll likely add continuous wrap then merge this code into the competition robot once all the other subsystems have been merged.

**Pull request merged**
